from .interface import HeadModule
from .contact_classifier import ContactPredictionHead
from .ppi_classifier import PPIPredictionHead
from .protein_classifier import ProteinClassificationHead
from .residue_classifier import ResidueClassificationHead