defaults:
  - _self_
  - model: mlp
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

data:
  embedding_type: esm
  data_dir: ${oc.env:DATA_DIR,data}
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

model:
  hidden_dims: [512, 256, 128]
  dropout_rate: 0.1
  learning_rate: 0.001
  weight_decay: 0.00001

training:
  batch_size: 32
  max_epochs: 100
  num_workers: 4
  precision: 16-mixed
  accelerator: gpu
  devices: 1
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0

seed: 42
output_dir: ${hydra:runtime.output_dir} 