tasks: ["GO:MF","GO:BP","GO:CC","EC"]
data_dir: "/weka/scratch/weka/kellislab/rcalef/data/magneton-data/evaluations"
model_params:
  hidden_dims: [256, 256, 256]
  dropout_rate: 0.1
  learning_rate: 1e-2
  weight_decay: 0.0