tasks: ["gb1", "beta_lactamase", "fluorescence", "fold", "solubility", "stability", "subcellular_localization", "thermostability", "binary_localization", "aav"]
data_dir: "${oc.env:MAGNETON_DATA_DIR}/evaluations"